// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
strategy("10+20 EMA Strategy", overlay=true, margin_long=10, margin_short=10, max_lines_count = 500)

ema10 = ta.ema(close, 10)
ema20 = ta.ema(close, 20)
ema200 = ta.ema(close, 200)
qty = 100000
riskPoints = 0.00250 
r2r = 2.0
lineLength = 20
crossoverWithinBars = 5
trendChangeWithinBars = 50
 
isBullish(i) =>
    close[i] > open[i]
isBearish(i) => 
    close[i] < open[i]
 
isInTrade = strategy.position_size != 0
isLong = strategy.position_size > 0
isShort = strategy.position_size < 0

barsSinceTrendChangeBullish = ta.barssince(ta.crossover(close, ema200))
barsSinceTrendChangeBearish = ta.barssince(ta.crossover(ema200, close))
isTrendChange = barsSinceTrendChangeBullish <= trendChangeWithinBars or barsSinceTrendChangeBearish <= trendChangeWithinBars

// Bullish
barsSinceBullishCrossover = ta.barssince(ta.crossover(ema10, ema20))
longSignal = barsSinceBullishCrossover <= crossoverWithinBars and isBearish(0) and close > ema10 // and ema10 > ema200 and not isTrendChange

if (longSignal and not isLong)
    if isShort
        strategy.cancel_all()
        strategy.close("Sell")

    takeProfitLevel = close + riskPoints * r2r
    stopLossLevel = close - riskPoints
    strategy.entry("Buy", strategy.long, qty)
    strategy.order("Buy take profit", strategy.short, qty, limit =  takeProfitLevel,oca_name = "Buy bracket", oca_type =  strategy.oca.cancel)
    strategy.order("Buy stop loss", strategy.short, qty, stop =  stopLossLevel, oca_name = "Buy bracket", oca_type =  strategy.oca.cancel)

    line.new(x1=bar_index, y1=open, x2=bar_index+lineLength, y2=open, color= color.blue)
    line.new(x1=bar_index, y1=takeProfitLevel, x2=bar_index+lineLength, y2=takeProfitLevel, color= color.green)
    line.new(x1=bar_index, y1=stopLossLevel, x2=bar_index+lineLength, y2=stopLossLevel, color= color.red)

// Bearish
// barsSinceBearishCrossover = ta.barssince(ta.crossover(ema20, ema10))
// shortSignal = barsSinceBearishCrossover <= crossoverWithinBars and isBullish(0) and close < ema10 and ema10 < ema200 and not isTrendChange

// if (shortSignal and not isShort)
//     if isLong
//         strategy.cancel_all()
//         strategy.close("Buy")

//     takeProfitLevel = close - riskPoints * r2r
//     stopLossLevel = close + riskPoints
//     strategy.entry("Sell", strategy.short, qty)
//     strategy.order("Sell take profit", strategy.long, qty, limit =  takeProfitLevel,oca_name = "Sell bracket", oca_type =  strategy.oca.cancel)
//     strategy.order("Sell stop loss", strategy.long, qty, stop =  stopLossLevel, oca_name = "Sell bracket", oca_type =  strategy.oca.cancel)

//     line.new(x1=bar_index, y1=open, x2=bar_index+lineLength, y2=open, color= color.blue)
//     line.new(x1=bar_index, y1=takeProfitLevel, x2=bar_index+lineLength, y2=takeProfitLevel, color= color.green)
//     line.new(x1=bar_index, y1=stopLossLevel, x2=bar_index+lineLength, y2=stopLossLevel, color= color.red)

