//@version=5
indicator("Candle Close Reversal", overlay=true)

// Since this is fixed at 3 bars to check against, it would be more accurate to not exit the loop early
// if a bar in the same direction is found as sometime between the two bars we are interested in, there 
// is a small bar that can break the loop early

barLookback = input.int(2, title="Candle Look Back", group= "Technical", minval = 1)
avgPeriods = input.int(20, title="Average Periods", group= "Technical", minval = 0)
avgBodySizeMultiplier = input.float(2.0, title="Average Body Size Multiplier", group= "Technical", step=0.1, minval = 0)
enableHighVol = input.bool(1, title="Enable High Volume Condition", group= "Technical")

avgVolume = ta.ema(volume, avgPeriods)
body = math.abs(open - close)
avgBody = ta.ema(body, avgPeriods)
isLargeBody = body > avgBody * avgBodySizeMultiplier

avgRange = ta.ema(high - low, avgPeriods)
isLargeRange(i) => 
    (high[i] - low[i]) > avgRange[i]

isBullish(i) =>
    close[i] > open[i]
isBearish(i) => 
    close[i] < open[i]

// Bullish close
mostRecentBearishHigh = 0.0
for i = 1 to barLookback
    if isBearish(i) and high[i] > mostRecentBearishHigh and (enableHighVol ? volume[i] > avgVolume[i] : 1)
        mostRecentBearishHigh := high[i]

isBullishClose(i) => 
    isBullish(i) and close[i] > mostRecentBearishHigh and isLargeRange(i)

isBullishCloseSignal = isBullishClose(0)
for i = 1 to barLookback
    if(isBullishClose(i))
        isBullishCloseSignal := false

// Bearish close
mostRecentBullishLow = 10000000.0
for i = 1 to barLookback
    if isBullish(i) and low[i] < mostRecentBullishLow and (enableHighVol ? volume[i] > avgVolume[i] : 1)
        mostRecentBullishLow := low[i]

isBearishClose(i) => 
    isBearish(i) and close[i] < mostRecentBullishLow and isLargeRange(i)

isBearishCloseSignal = isBearishClose(0)
for i = 1 to barLookback
    if(isBearishClose(i))
        isBearishCloseSignal := false

// Plot all the things
plotshape(isBullishCloseSignal, style=shape.circle, location=location.belowbar, color=color.green, size=size.tiny)

plotshape(isBearishCloseSignal, style=shape.circle, location=location.abovebar, color=color.red, size=size.tiny)