// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Close Beyond Last Opposite Candle", overlay = true)

lookback = input.int(5, "Lookback")

highestBearish = 0.0
lowestBullish = 10000000.0
var isBullishClose = false
var isBearishClose = false

isBullish(i) =>
    close[i] > open[i]
isBearish(i) =>
    close[i] < open[i]

for i = 1 to lookback
    if(isBullish(i))
        lowestBullish := low[i]
        break

for i = 1 to lookback
    if(isBearish(i))
        highestBearish := high[i]
        break

isBullishClose := isBullish(0) and close > highestBearish
isBearishClose := isBearish(0) and close < lowestBullish


// Only mark the first time it happens, not successive events looking at the same opposite candle
plotshape(isBullishClose and not isBullishClose[1], style=shape.circle, location=location.belowbar, color=color.green, size=size.tiny)
plotshape(isBearishClose and not isBearishClose[1], style=shape.circle, location=location.abovebar, color=color.red, size=size.tiny)


