//@version=5
indicator("Candle Close Highlight", overlay=true)

avgVolume = ta.ema(volume, 20)

// Bullish close
isBullish = close > open

recentBearishHighWithHiVol = high
for i = 1 to 3
    if close[i] < open[i] and volume[i] > avgVolume[i]
        recentBearishHighWithHiVol := high[i]
        break

isBullishClose = isBullish and close > recentBearishHighWithHiVol

// Bearish close
isBearish = close < open

recentBullishLowWithHiVol = low
for i = 1 to 3
    if close[i] > open[i] and volume[i] > avgVolume[i]
        recentBullishLowWithHiVol := low[i]
        break

isBearishClose = isBearish and close < recentBullishLowWithHiVol

// Bullish breakout
highestRecentHigh(count) => 
    temp = array.new_float(count)
    for i = 0 to count - 1
        array.set(temp, i, high[i+1])

    array.max(temp) // returned

high3 = highestRecentHigh(3)
isBullishBreakout = close > high3 and low <= low3

// Bearish breakout
lowestRecentLow(count) => 
    temp = array.new_float(count)
    for i = 0 to count - 1
        array.set(temp, i, low[i+1])

    array.min(temp) // returned

low3 = lowestRecentLow(3)
isBearishBreakout = close <low3 and high >= high3

// Plot all the things
plotshape(isBullishClose, style=shape.circle, location=location.belowbar, color=color.green, size=size.tiny)

plotshape(isBearishClose, style=shape.circle, location=location.abovebar, color=color.red, size=size.tiny)

plotshape(isBullishBreakout, style=shape.circle, location=location.belowbar, color=color.yellow, size=size.tiny)

plotshape(isBearishBreakout, style=shape.circle, location=location.abovebar, color=color.yellow, size=size.tiny)