// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Close Beyond Previous Candle", overlay = false)



isBullish = close > high[1]
isBearish = close < low[1]

plotValue = 0.0
plotColour = color.gray
var cumulativeValue = 0.0

if(isBullish)
    cumulativeValue += close - high[1]
    plotValue := cumulativeValue
    plotColour := color.green
else if(isBearish)
    cumulativeValue += close - low[1]
    plotValue := cumulativeValue
    plotColour := color.red
else
    plotValue := plotValue[1]
    plotColour := color.gray

plot(plotValue, color = plotColour, style = plot.style_line, linewidth = 3)