// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Directional Strength", overlay = false, precision = 5)

lookback = input.int(5, "Candle lookback")

highest = ta.highest(lookback)
lowest = ta.lowest(lookback)
average = ta.sma(close, lookback)

plot((close - highest)/average, color = color.red, linewidth = 1)
plot((close - lowest)/average, color = color.green, linewidth = 1)
hline(0.0, linestyle = hline.style_dashed, color = color.gray)