// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Doji Pivot", overlay = true, max_labels_count = 500)

pivotBarLength = input(4, title="Bars either side of pivot", group= "Technical")
minWickProportion = input.float(0.2, title="Minimum wick proportion", group= "Technical", step=0.1)
maxBodyProportion = input.float(0.2, title="Maximum body proportion", group= "Technical", step=0.1)

addLabel(int offset) => 

    isBullish = close[offset] > open[offset]
    fullRange = high[offset] - low[offset]
    body = math.abs(open[offset] - close[offset])

    upperWick = isBullish ? high[offset] - close[offset] : high[offset] - open[offset]
    lowerWick = isBullish ? open[offset] - low[offset] : close[offset] - low[offset]

    hasLargeUpperWick = upperWick >= fullRange * minWickProportion
    hasLargeLowerWick = lowerWick >= fullRange * minWickProportion

    if(hasLargeLowerWick and hasLargeUpperWick)
        label.new(bar_index - offset, high[pivotBarLength], yloc=yloc.abovebar, style=label.style_triangledown)

//    hasSmallBody = body < fullRange * maxBodyProportion

//    if(hasSmallBody)    
//        label.new(bar_index - offset, high[pivotBarLength], yloc=yloc.belowbar, style=label.style_diamond)

// Find pivot outside `if` block because needs to run on every bar.
pivotHigh = ta.pivothigh(pivotBarLength, pivotBarLength)
pivotLow = ta.pivotlow(pivotBarLength, pivotBarLength)

// Detect a new pivot.
newPivotHigh = not na(pivotHigh)
newPivotLow = not na(pivotLow)

if(newPivotHigh or newPivotLow)
    addLabel(pivotBarLength)