//@version=5
indicator('Double Top/Bottom', overlay=true)
pivotLegs = 3
length=10

// Find pivot outside `if` block because needs to run on every bar.
pivotHigh = ta.pivothigh(pivotLegs, pivotLegs)
pivotLow = ta.pivotlow(pivotLegs, pivotLegs)
// Detect a new pivot.
newPivotHigh = not na(pivotHigh)
newPivotLow = not na(pivotLow)
// If a new pivot is found, save the bar index where it was found.
barIndexHighPivot = newPivotHigh ? bar_index - pivotLegs : na
barIndexLowPivot = newPivotLow ? bar_index - pivotLegs : na

if newPivotHigh
    label.new(barIndexHighPivot, high[pivotLegs], yloc=yloc.abovebar, style=label.style_triangledown)
if newPivotLow
    label.new(barIndexLowPivot, low[pivotLegs], yloc=yloc.belowbar, style=label.style_triangleup)

// Need to detect when two are close together as that may be a double top/bottom
// Probably need to search back through the series to check, last continually gets cleared
plot(bar_index)
test2 = ta.valuewhen(not na(barIndexHighPivot), barIndexHighPivot, 0)
test3 = ta.valuewhen(not na(barIndexHighPivot), barIndexHighPivot, 1)
plot(test2)
plot(test3)