// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Engulfing Reversal", overlay = true)

isBullish(i) => close[i] > open[i]
isBearish(i) => close[i] < open[i]

isEngulfing(i) => high[i] > high[i+1] and low[i] < low[i+1]
isStrongBullishClose(i) => isBullish(i) and close[i] > high[i+1]
isStrongBearishClose(i) => isBearish(i) and close[i] < low[i+1]
isBullishEngulfing(i) => isBullish(i) and isEngulfing(i)
isBearishEngulfing(i) => isBearish(i) and isEngulfing(i)

plotshape(isBullishEngulfing(0) and isStrongBullishClose(0) and isBearish(1), style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny)
plotshape(isBearishEngulfing(0) and isStrongBearishClose(0) and isBullish(1), style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny)

