// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
// Red gap highlight means bearish, green mean bullish. Based off Retest Gap and Gap and Go from RLT.
indicator("Gap Highlighter", overlay=true, max_boxes_count=500)

minGapSize = input(1.0, title="Minimum gap size", group= "Technical")
transparency = 50
bullishColour = color.new(color.green, transparency)
bearishColour = color.new(color.red, transparency)
neutralColour = color.new(color.yellow, transparency)

isYesterdayBullish = close[1] > open[1]

isGapDown = open < close[1] - minGapSize

gapDownTop = isGapDown ? close[1] : na
gapDownBottom = isGapDown ? open : na

gapDownColour = isYesterdayBullish ? bearishColour : neutralColour

box.new(bar_index[1], gapDownTop, bar_index, gapDownBottom, bgcolor=gapDownColour, border_color=gapDownColour)

gapUp = open > close[1] + minGapSize

gapUpTop = gapUp ? open : na
gapUpBottom = gapUp ? close[1] : na

gapUpColour = isYesterdayBullish ? neutralColour : bullishColour

box.new(bar_index[1], gapUpTop, bar_index, gapUpBottom, bgcolor=gapUpColour, border_color=gapUpColour)

