// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("High Volume Bar", overlay = true)

avgPeriods = input.int(20, title="Average Periods", group= "Technical", minval = 0)
avgVolumeMultiplier = input.float(1.5, title="Average Volume Multiplier", group= "Technical", step=0.1, minval = 0)

isBullish(i) =>
    close[i] > open[i]
isBearish(i) => 
    close[i] < open[i]

avgVolume = ta.sma(volume, avgPeriods)

isHighVolume = volume >= avgVolume * avgVolumeMultiplier

barcolor(isHighVolume and isBullish(0) ? color.green : na)
barcolor(isHighVolume and isBearish(0) ? color.red : na)

