// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("High Volume Stop Losses", overlay = true, max_lines_count = 500)

avgPeriods = input.int(100, title="Average periods", minval = 0)
highVolumeMultiple = input.float(3.0, title="High volume threshold (multiples)", minval = 0, step = 0.1)
lineExtensionLength = input.int(100, "Line extension length")
highBullishVolumeColour = input.color(color.green, "High bullish volume colour")
highBearishVolumeColour = input.color(color.red, "High bearish volume colour")

isBullish(offset) =>
    close[offset] > open[offset]
isBearish(i) => 
    close[i] < open[i]

avgVolume = ta.sma(volume, avgPeriods) 
volumeMultiple = volume / avgVolume

isHighVolume = volumeMultiple >= highVolumeMultiple

if(isBullish(0) and isHighVolume)
    line.new(x1=bar_index, y1=low, x2=bar_index+lineExtensionLength, y2=low, color= highBullishVolumeColour, style = line.style_dashed, width = 2)

if(isBearish(0) and isHighVolume)
    line.new(x1=bar_index, y1=high, x2=bar_index+lineExtensionLength, y2=high, color= highBearishVolumeColour, style = line.style_dashed, width = 2)