// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=6
indicator("High ATR", overlay = true)

atrPeriod = input.int(20, "ATR periods")
atrMultiplier = input.float(2, "ATR multiplier")

barRange = high - low
isBullish = close > open

highAtr = barRange > ta.atr(atrPeriod)*atrMultiplier

plotshape(highAtr and isBullish, style=shape.circle, location= location.belowbar , color= color.green, size=size.tiny)
plotshape(highAtr and not isBullish, style=shape.circle, location= location.abovebar , color= color.red, size=size.tiny)

plot(ta.atr(atrPeriod))
plot(high-low)