// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("LS Reaction", overlay = true)

isHighSweep(i)=>
    high[i] > high[i+1] and open[i] <= high[i+1]

isLowSweep(i) => 
    low[i] < low[i+1] and open[i] >= low[i+1]

isCurrentBarReactionBearish = close < low[1]
isCurrentBarReactionBullish = close > high[1]


/////////////
bodySizeAvg = input.int(5, "Average")
largeBodySizeMultiplier = input.float(2, "Large body size multiplier", step=0.1)

bodySize(i) =>
    math.abs(open[i] - close[i])

avgBodySize = ta.sma(bodySize(0), bodySizeAvg)

isCurrentBarLargeBodySize = bodySize(0) >= avgBodySize * largeBodySizeMultiplier
////////////

plotshape(isHighSweep(1) and isCurrentBarReactionBearish and isCurrentBarLargeBodySize, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny)
plotshape(isLowSweep(1) and isCurrentBarReactionBullish and isCurrentBarLargeBodySize, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny)

//////////////////////////
// Too many matches to be useful
// isCurrentBarReactionWeakBullish = close < high[1]
// isCurrentBarReactionWeakBearish = close > low[1]
// plotshape(isLowSweep(1) and isCurrentBarReactionWeakBullish, style=shape.cross, location=location.abovebar, color=color.gray, size=size.tiny)
// plotshape(isHighSweep(1) and isCurrentBarReactionWeakBearish, style=shape.cross, location=location.belowbar, color=color.gray, size=size.tiny)
