// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=6
indicator("Momentum")

period = input.int(3, "Period")

isBullish = close > open
isBearish = close < open

hline(0, color = color.black, linestyle = hline.style_solid)
bullishBodyTotal = math.sum(isBullish ? close - open : 0, period)
bearishBodyTotal = math.sum(isBearish ? close - open : 0, period)

bodyTotal = bullishBodyTotal + bearishBodyTotal
standardColour = color.new(color.blue, 50)
plot(bodyTotal, color = standardColour, style = plot.style_area)

upColour = color.new(color.green, 50)
downColour = color.new(color.red, 50)
plot(bodyTotal > 0 ? bodyTotal : math.abs(bodyTotal), color = bodyTotal > 0 ? upColour : downColour, style = plot.style_area)

