// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=6
indicator("My Cumulative Volume Delta", max_lines_count = 500)

import TradingView/ta/8

[openVolume, maxVolume, minVolume, lastVolume] = ta.requestVolumeDelta("1", "1M")

isBullishCVD = lastVolume > openVolume

plotcandle(openVolume, maxVolume, minVolume, lastVolume, "My CVD", lastVolume >= openVolume ? color.green : color.red)

volCandleRange = math.abs (maxVolume - minVolume)
volCandleBody = math.abs (openVolume - lastVolume)

avgCandleBody = ta.sma(volCandleBody, 10)

// Large candle
isLargeBullish = isBullishCVD and volCandleBody >= 2* avgCandleBody 

if (isLargeBullish)
    line.new(x1 = bar_index, y1=low, x2=bar_index + 20, y2= low, style=line.style_dashed, color=color.green, width = 2, force_overlay = true)

isLargeBearish = not isBullishCVD and volCandleBody >= 2* avgCandleBody 

if (isLargeBearish)
    line.new(x1 = bar_index, y1=high, x2=bar_index + 20, y2= high, style=line.style_dashed, color=color.red, width = 2, force_overlay = true)


var float lastBullishSize = na
var float lastBearishSize = na

bullishSize = isBullishCVD ? volCandleBody : lastBullishSize
bearishSize = not isBullishCVD ? volCandleBody : lastBearishSize

plot(bullishSize, "Bullish Body", color = color.green)
plot(bearishSize, "Bearish Body", color = color.red)

if(isBullishCVD)
    lastBullishSize := bullishSize
if(not isBullishCVD)
    lastBearishSize := bearishSize

hline(0, color = #787b864f, linestyle = hline.style_solid, linewidth = 2)