// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("One White Soldier", overlay = true)

avgPeriods = input.int(20, title="Average Periods", group= "Technical", minval = 0)
avgBodySizeMultiplier = input.float(1.0, title="Average Body Size Multiplier", group= "Technical", step=0.1, minval = 0)

avgVolume = ta.sma(volume, avgPeriods) 
avgRange = ta.ema(high - low, avgPeriods)

isLargeRange(i) => 
    (high[i] - low[i]) > avgRange[i] * avgBodySizeMultiplier

isBullish(i) =>
    close[i] > open[i]
isBearish(i) => 
    close[i] < open[i]

isOWS = isBullish(0) and isBearish(1) and close > high[1] and open > close[1] and isLargeRange(0) and isLargeRange(1)

isOBC = isBullish(1) and isBearish(0) and close < low[1] and open < close[1] and isLargeRange(0) and isLargeRange(1) // is One Black Crow

plotshape(isOWS, style=shape.circle, location=location.belowbar, color=color.yellow, size=size.tiny)
plotshape(isOBC, style=shape.circle, location=location.abovebar, color=color.yellow, size=size.tiny)
