// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Surge", overlay = true, max_boxes_count = 500)

lookback = input.int(2, "Candle lookback")

// Defaults for XAUUSD
minSurge1m = input.float(0.9, title="1m", group = "Surge minimum", minval = 0, step = 1)
minSurge5m = input.float(5, title="5m", group = "Surge minimum", minval = 0, step = 1)
minSurge15m = input.float(8, title="15m", group = "Surge minimum", minval = 0, step = 1)
minSurge1h = input.float(10, title="1h", group = "Surge minimum", minval = 0, step = 1)
minSurge1d = input.float(50, title="1D", group = "Surge minimum", minval = 0, step = 1)

timeframeMinutes = timeframe.in_seconds()/60
isTimeframeHours = timeframeMinutes >= 60

minSurge = switch timeframeMinutes
    1 => minSurge1m
    5 => minSurge5m
    15 => minSurge15m
    60 => minSurge1h
    86400 => minSurge1d
    => minSurge1h


bullishHighlightColour = input.color(color.new(#03f80c, 60), title="Bullish Highlight Colour")
bearishHighlightColour = input.color(color.new(#f60404, 80), title="Bearish Highlight Colour")

isBullish(i) =>
    close[i] > open[i]

lowestCloseLookback = ta.lowest(close, lookback+1) // The function includes the current candle, so add one to get actual lookback
highestCloseLookback = ta.highest(close, lookback+1)

priceDiff = isBullish(0) ? close - lowestCloseLookback : highestCloseLookback - close

isSurgeUp = priceDiff >= minSurge and isBullish(0)
isSurgeDown = priceDiff >= minSurge and not isBullish(0)

if(isSurgeUp)
    box.new(bar_index - lookback, lowestCloseLookback, bar_index, highestCloseLookback, bgcolor=bullishHighlightColour, border_color = na)
if(isSurgeDown)
    box.new(bar_index - lookback, highestCloseLookback, bar_index, lowestCloseLookback, bgcolor=bearishHighlightColour, border_color = na)
