// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Surge", overlay = true, max_boxes_count = 500)


lookback = input.int(5, "Candle lookback")
minSurgeUp = input.float(0.01000, "Surge minimum up", step=0.00100)
minSurgeDown = input.float(0.01200, "Surge minimum down", step=0.00100)
bullishHighlightColour = input.color(color.new(#03f80c, 60), title="Bullish Highlight Colour")
bearishHighlightColour = input.color(color.new(#f60404, 80), title="Bearish Highlight Colour")

isBullish(i) =>
    close[i] > open[i]

lowestCloseLookback = ta.lowest(close, lookback+1) // The function includes the current candle, so add one to get actual lookback
highestCloseLookback = ta.highest(close, lookback+1)

priceDiff = isBullish(0) ? close - lowestCloseLookback : highestCloseLookback - close

isSurgeUp = priceDiff >= minSurgeUp and isBullish(0)
isSurgeDown = priceDiff >= minSurgeDown and not isBullish(0)

if(isSurgeUp)
    box.new(bar_index - lookback, lowestCloseLookback, bar_index, highestCloseLookback, bgcolor=bullishHighlightColour, border_color = na)
if(isSurgeDown)
    box.new(bar_index - lookback, highestCloseLookback, bar_index, lowestCloseLookback, bgcolor=bearishHighlightColour, border_color = na)

// plot(priceDiff)