// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=6
indicator("Trend Forming", overlay = true)
import TradingView/ta/9

sequentialCandleCount = input.int(2, "Sequential number of candles to define a trend")
atrPeriod = input.int(5, "ATR period")

atr = ta.atr(atrPeriod)
candleRange = high - low

isBullishTrendCandle(i) => 
    close[i] > high[i+1] and (low[i] > low[i+1] or low[i] > low[i+2]) and candleRange[i] >= atr[i]
isBearishTrendCandle(i) => 
    close[i] < low[i+1] and (high[i] < high[i+1] or high[i] < high[i+2]) and candleRange[i] >= atr[i]

// plotshape(isBearishTrendCandle(0), style=shape.circle, location=location.abovebar, color=color.blue, size=size.tiny)
isBullishTrendCount = 0
for i=0 to sequentialCandleCount-1
    if isBullishTrendCandle(i)
        isBullishTrendCount += 1

isBearishTrendCount = 0
for i=0 to sequentialCandleCount-1
    if isBearishTrendCandle(i)
        isBearishTrendCount += 1

isBullishTrend = isBullishTrendCount >= sequentialCandleCount
isBearishTrend = isBearishTrendCount >= sequentialCandleCount

plotshape(isBullishTrend, style=shape.circle, location=location.belowbar, color=color.green, size=size.tiny)
plotshape(isBearishTrend, style=shape.circle, location=location.abovebar, color=color.red, size=size.tiny)

alertcondition(isBullishTrend,"Trend forming","Bullish")
alertcondition(isBearishTrend,"Trend forming","Bearish")
