//@version=5

indicator('Volume High Standard Deviation', shorttitle='Vol Hi Std Dev', overlay=true, precision=1)

len = input.int(title='Length', minval=1, defval=20, maxval=999, group='Technical')

sigmaThreshold = input.float(title='Sigma Threshold', minval=-2, defval=1.5, maxval=4, group='Technical', step=0.1)

sigma = (volume - ta.sma(volume, len)) / ta.stdev(volume, len)

isBullish = close > open
volLarge = volume > 0 ? sigma >= sigmaThreshold : 0

plotshape(isBullish and volLarge, style=shape.square, location=location.abovebar, color=color.new(color.green, 0), size=size.tiny)

plotshape(not isBullish and volLarge, style=shape.square, location=location.belowbar, color=color.new(color.red, 0), size=size.tiny)

if isBullish and volLarge
    line.new(x1=bar_index, y1=high, x2=bar_index + 5 * len, y2=high, color=color.green)

if not isBullish and volLarge
    line.new(x1=bar_index, y1=low, x2=bar_index + 5 * len, y2=low, color=color.red)

