// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Volume and Body Multiples")

avgPeriods = input.int(100, title="Average Periods", group= "Technical", minval = 0)
highVolume = input.float(3.0, title="High Volume Threshold", group= "Technical", minval = 0, step = 0.1)
largeBody = input.float(4.5, title="Large Body Threshold", group= "Technical", minval = 0, step = 0.1)

avgVolume = ta.sma(volume, avgPeriods) 
volumeMultiple = volume / avgVolume
plot(volumeMultiple, "Volume multiple", color = color.blue)
hline(highVolume, color = color.blue)

bodySize = math.abs(close - open)
avgBodySize = ta.sma(bodySize, avgPeriods)
bodyMultiple = bodySize / avgBodySize
plot(bodyMultiple, "Body multiple", color = color.red)
hline(largeBody, color = color.red)

alertcondition(volumeMultiple >= highVolume, "High Volume", "High volume")
alertcondition(bodyMultiple >= largeBody, "Large Body", "Large body")