//@version=4

study("Volume High Standard Deviation", shorttitle="Vol Hi Std Dev", 
     overlay=true, precision=1)

len= input(title="Length", type=input.integer, 
     minval=1, defval=20, maxval=999, group= "Technical")

sigmaThreshold= input(title="Sigma Threshold", type=input.float, 
     minval=-2, defval=1.5, maxval=4, group= "Technical", step=0.1)

sigma =  (volume-sma(volume,len))/stdev(volume, len)

isBullish = close > open
volLarge = volume > 0 ? sigma >= sigmaThreshold : 0

plotshape(isBullish and volLarge, style = shape.square,  location=location.abovebar, color=color.green, size=size.tiny)

plotshape(not isBullish and volLarge, style=shape.square, location=location.belowbar, color=color.red, size=size.tiny)

if (isBullish and volLarge)
    line.new(x1=bar_index, y1=high,
         x2=bar_index + 5*len, y2=high, color=color.green)

if (not isBullish and volLarge)
    line.new(x1=bar_index, y1=low,
         x2=bar_index + 5*len, y2=low, color=color.red)