// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Wick Shadow", overlay = true, max_boxes_count = 500)

shadowColour = input.color(color.rgb(94, 39, 176), title="Shadow Colour", group= "Technical")
normalTransparency = input(80, title="Shadow Transparency", group= "Technical")
highVolumeTransparency = input(30, title="High Volume Shadow Transparency", group= "Technical")
minWickProportion = input.float(0.3, title="Minimum wick proportion", group= "Technical", step=0.1)
normalShadowSize = input(20, title="Shadow Length", group= "Technical")
highVolumeShadowSize = input(200, title="High Volume Shadow Length", group= "Technical")
volumeAvgPeriods = input(20, title="Volume Average Periods", group= "Technical")
minAvgMultiplier = input.float(1.3, title="Minimum Average Multiplier", group= "Technical", step=0.1)

isHighVolume = volume > 0 and volume >= ta.ema(volume, volumeAvgPeriods) * minAvgMultiplier

transparency = isHighVolume ? highVolumeTransparency : normalTransparency
shadowSize = isHighVolume ? highVolumeShadowSize : normalShadowSize

bullishColour = color.new(shadowColour, transparency)
bearishColour = color.new(shadowColour, transparency)

isBullish = close > open
body = math.abs(open - close)
fullRange = high - low
upperWick = isBullish ? high - close : high - open
lowerWick = isBullish ? open - low : close - low

// Bearish wick
isBearishWick = upperWick >= fullRange * minWickProportion

BearishWickTop = isBearishWick ? high : na
BearishWickBottom = isBearishWick ? (isBullish ? close : open) : na

box.new(bar_index, BearishWickTop, bar_index + shadowSize, BearishWickBottom, bgcolor=bearishColour, border_color=bearishColour)

// Bullish wick
isBullishWick = lowerWick >= fullRange * minWickProportion

BullishWickTop = isBullishWick ? (isBullish ? open : close) : na
BullishWickBottom = isBullishWick ? low : na

box.new(bar_index, BullishWickTop, bar_index + 100, BullishWickBottom, bgcolor=bullishColour, border_color=bullishColour)