// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © glenrutherford4

//@version=5
indicator("Wick Size", overlay = false)

maPeriods = input.int(100, "Moving average periods")
maMultiplier = input.float(1, "Moving average multiplier")

isBullish = close >= open

totalWickSize = isBullish ? high - close + open - low : high - open + close - low
plot(totalWickSize, color = color.red)
plot(ta.sma(totalWickSize, maPeriods) * maMultiplier, color = color.blue)
